### PR TITLE
import .clang-format to follow the style presented in Contributing.md…

### PR DESCRIPTION
**Pull request by dBitech**
…  Put framework inplace to have git-precommit hooks enabled.

apply-format and git-pre-commit-format imported from: https://github.com/barisione/clang-format-hooks/

### CODE REVIEW

**Comment by hoche** [comment]
Oh. Ok, how about we allow a couple more days of thrash and then I'll do the merge?

**Comment by der-stefan** [comment]
Wow, a lot of code for formatting code. Do we really need this in the repository? 🤷 For sure I don't have much experience in collaborative software engineering. 🤐

**Comment by dBitech** [comment]
The thought here was to have a framework in place that would "force" the correct code style to be applied as part of the commit phase in an effort to ensure the repo stays clean.  This is especially true when there is mixed *nix and MSwindows developers (pesky ^M's)

**Comment by der-stefan** [comment]
Ok, got it. However, I very much dislike the current format. Here is a bad example:
````
                                    terrain =
                                        (unsigned)(0.5 +
                                                   pow((double)(dem->data
                                                                    [x0 *
                                                                         sr.ippd +
                                                                     y0] -
                                                                em.min_elevation),
                                                       one_over_gamma) *
                                                       conversion);
````
As I'm not working on an old 800 x 600 CRT display anymore, please let's write it in one line. And if your monitor is not wide enough, tell your text editor to break visually.
````
terrain = (unsigned)(0.5 + pow((double)(dem->data[x0 *  sr.ippd + y0] - em.min_elevation), one_over_gamma) * conversion);
````

**Comment by hoche** [comment]
That kind of line break isn't something the formatter would mess with. It's left up to the author because sometimes the line breaks are needed for clarity. In this particular case, yeah it's a bit overkill and can be reformatted.

Personally, I try to keep it to under 120 chars wide, mostly because then I can keep multiple windows up on my screen side-by-side without undue eyestrain.

**Comment by dBitech** [comment]
the mechanics of where the line breaks are enforced, or the bracket placements can easily be modified within the .clang-format, To be fair I grabbed existing one from one of my other projects modified it to try and match what I saw in the existing code base, hinted by [Contributing.md](https://github.com/hoche/splat/blob/refactor/Contributing.md)

**Comment by watkipet** [comment]
I'm not sure what the status is here. @hoche, the .clang-format you checked in is much simpler than the one presented here. Is that what you'd like to stay with? Did you want this .clang-format updated with changes from yours? The biggest conflict I see is that @dBitech's .clang-format is based on `google` whereas the one you checked in is based on `LLVM`.

**Comment by dBitech** [comment]
I have no strong personal preference for the style used, as long as there is one that is associated with the project.

**Comment by hoche** [comment]
I think the one supplied here is too strict. For instance, the BraceWrapping:AfterCaseLabel setting would really annoy me. Sometimes I use the compact form and sometimes I put braces on their own line - it depends on how long the block is and how readable I think it's going to be.

**Pull request closed without merging**
